# Generated by Django 3.0.7 on 2020-07-16 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pid', models.IntegerField()),
                ('description', models.TextField()),
                ('contents', models.CharField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
