# Generated by Django 3.0.7 on 2020-07-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DoctorName', models.CharField(max_length=256)),
                ('DLicense', models.CharField(max_length=256)),
                ('HospitalName', models.CharField(max_length=256)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=256)),
                ('State', models.CharField(max_length=256)),
                ('PinCode', models.IntegerField()),
                ('Contactno', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MownerName', models.CharField(max_length=256)),
                ('MLicense', models.CharField(max_length=256)),
                ('MedicalName', models.CharField(max_length=256)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=256)),
                ('State', models.CharField(max_length=256)),
                ('PinCode', models.IntegerField()),
                ('Contactno', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerName', models.CharField(max_length=256)),
                ('OLicense', models.CharField(max_length=256)),
                ('OrgName', models.CharField(max_length=256)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=256)),
                ('State', models.CharField(max_length=256)),
                ('PinCode', models.IntegerField()),
                ('Contactno', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
