# Generated by Django 3.0.7 on 2020-07-18 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0002_doctor_medical_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Maximum_quantity', models.IntegerField(default=1000)),
                ('current_quantity', models.IntegerField()),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataapp.Product')),
            ],
        ),
    ]
