# Generated by Django 3.0.7 on 2020-07-23 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0003_stocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quater1_sale', models.IntegerField(blank=True, null=True)),
                ('quater2_sale', models.IntegerField(blank=True, null=True)),
                ('quater3_sale', models.IntegerField(blank=True, null=True)),
                ('quater4_sale', models.IntegerField(blank=True, null=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataapp.Product')),
            ],
        ),
    ]
