# Generated by Django 3.1.4 on 2021-03-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='organisation',
        ),
    ]
